// generated by ng_file_service_ts
import { Injectable, Component, Inject } from '@angular/core';
import { HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { DOCUMENT, Location } from '@angular/common'

/*
 * Behavior subject
 */
import { BehaviorSubject } from 'rxjs'
import { Observable, of } from 'rxjs'
import { catchError, map, tap } from 'rxjs/operators'

import { CountryAPI } from './country-api'
import { Country, CopyCountryToCountryAPI } from './country'

import { FrontRepo, FrontRepoService } from './front-repo.service';

// insertion point for imports
import { HelloAPI } from './hello-api'

@Injectable({
  providedIn: 'root'
})
export class CountryService {

  // Kamar Raïmo: Adding a way to communicate between components that share information
  // so that they are notified of a change.
  CountryServiceChanged: BehaviorSubject<string> = new BehaviorSubject("");

  private countrysUrl: string

  constructor(
    private http: HttpClient,
    @Inject(DOCUMENT) private document: Document
  ) {
    // path to the service share the same origin with the path to the document
    // get the origin in the URL to the document
    let origin = this.document.location.origin

    // if debugging with ng, replace 4200 with 8080
    origin = origin.replace("4200", "8080")

    // compute path to the service
    this.countrysUrl = origin + '/api/gongng18/go/v1/countrys';
  }

  /** GET countrys from the server */
  // gets is more robust to refactoring
  gets(GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryAPI[]> {
    return this.getCountrys(GONG__StackPath, frontRepo)
  }
  getCountrys(GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryAPI[]> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    return this.http.get<CountryAPI[]>(this.countrysUrl, { params: params })
      .pipe(
        tap(),
        catchError(this.handleError<CountryAPI[]>('getCountrys', []))
      );
  }

  /** GET country by id. Will 404 if id not found */
  // more robust API to refactoring
  get(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryAPI> {
    return this.getCountry(id, GONG__StackPath, frontRepo)
  }
  getCountry(id: number, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)

    const url = `${this.countrysUrl}/${id}`;
    return this.http.get<CountryAPI>(url, { params: params }).pipe(
      // tap(_ => this.log(`fetched country id=${id}`)),
      catchError(this.handleError<CountryAPI>(`getCountry id=${id}`))
    );
  }

  // postFront copy country to a version with encoded pointers and post to the back
  postFront(country: Country, GONG__StackPath: string): Observable<CountryAPI> {
    let countryAPI = new CountryAPI
    CopyCountryToCountryAPI(country, countryAPI)
    const id = typeof countryAPI === 'number' ? countryAPI : countryAPI.ID
    const url = `${this.countrysUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<CountryAPI>(url, countryAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<CountryAPI>('postCountry'))
    );
  }
  
  /** POST: add a new country to the server */
  post(countrydb: CountryAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryAPI> {
    return this.postCountry(countrydb, GONG__StackPath, frontRepo)
  }
  postCountry(countrydb: CountryAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryAPI> {

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.post<CountryAPI>(this.countrysUrl, countrydb, httpOptions).pipe(
      tap(_ => {
        // this.log(`posted countrydb id=${countrydb.ID}`)
      }),
      catchError(this.handleError<CountryAPI>('postCountry'))
    );
  }

  /** DELETE: delete the countrydb from the server */
  delete(countrydb: CountryAPI | number, GONG__StackPath: string): Observable<CountryAPI> {
    return this.deleteCountry(countrydb, GONG__StackPath)
  }
  deleteCountry(countrydb: CountryAPI | number, GONG__StackPath: string): Observable<CountryAPI> {
    const id = typeof countrydb === 'number' ? countrydb : countrydb.ID;
    const url = `${this.countrysUrl}/${id}`;

    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.delete<CountryAPI>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted countrydb id=${id}`)),
      catchError(this.handleError<CountryAPI>('deleteCountry'))
    );
  }

  // updateFront copy country to a version with encoded pointers and update to the back
  updateFront(country: Country, GONG__StackPath: string): Observable<CountryAPI> {
    let countryAPI = new CountryAPI
    CopyCountryToCountryAPI(country, countryAPI)
    const id = typeof countryAPI === 'number' ? countryAPI : countryAPI.ID
    const url = `${this.countrysUrl}/${id}`;
    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    }

    return this.http.put<CountryAPI>(url, countryAPI, httpOptions).pipe(
      tap(_ => {
      }),
      catchError(this.handleError<CountryAPI>('updateCountry'))
    );
  }

  /** PUT: update the countrydb on the server */
  update(countrydb: CountryAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryAPI> {
    return this.updateCountry(countrydb, GONG__StackPath, frontRepo)
  }
  updateCountry(countrydb: CountryAPI, GONG__StackPath: string, frontRepo: FrontRepo): Observable<CountryAPI> {
    const id = typeof countrydb === 'number' ? countrydb : countrydb.ID;
    const url = `${this.countrysUrl}/${id}`;


    let params = new HttpParams().set("GONG__StackPath", GONG__StackPath)
    let httpOptions = {
      headers: new HttpHeaders({ 'Content-Type': 'application/json' }),
      params: params
    };

    return this.http.put<CountryAPI>(url, countrydb, httpOptions).pipe(
      tap(_ => {
        // this.log(`updated countrydb id=${countrydb.ID}`)
      }),
      catchError(this.handleError<CountryAPI>('updateCountry'))
    );
  }

  /**
   * Handle Http operation that failed.
   * Let the app continue.
   * @param operation - name of the operation that failed
   * @param result - optional value to return as the observable result
   */
  private handleError<T>(operation = 'operation in CountryService', result?: T) {
    return (error: any): Observable<T> => {

      // TODO: send the error to remote logging infrastructure
      console.error("CountryService" + error); // log to console instead

      // TODO: better job of transforming error for user consumption
      this.log(`${operation} failed: ${error.message}`);

      // Let the app keep running by returning an empty result.
      return of(result as T);
    };
  }

  private log(message: string) {
    console.log(message)
  }
}
